deploy:
  provider: heroku
  language: ruby
  rvm:
    - 2.3.1
  api_key:
    secure: pegKyMbeLb8pA3Omnd+nbJY5/jEl8l6gUYZaMtWq0V6LIFKKOUoMmqGb5FcDH7W3Jbt49mDptn1WOrxD2/ippzHalbfytScv9IhtgoyRcxWj4Df872rirWTmLApQWTVVkui0qbdDfkf42dLWTFxJ/pT3FSPp8WPkqwXlkDz8cLIukv77a3Cv59GeFNNmKh1td2xnIIFlPq6zjBF6OwunwhXcBCmBzY1Ks6mX1bKelIQu6YDNd3e0XmnTy4NNshZOPPEhK/N7CJezjN4lFxuyT/0ZOJNpY85oOuf5ozAUKYr7g5pIGBLpwNHMIFyKWGkzubBlHUL9VsskAe7kZjlHyLbYAPjysDMqqV0919YSeo9z7fFbWoei5rdL8yz2xgsi2V6S8IfqhoY5GRlvpPKno+a9DUSuqBM2FinbwoMFy9K0vKcma53vtGhueUgz2asVL8hI/KxyajQctk7xKzAOxv64w8oQlSxVDJgNYkkO+6GxTPj8c6okrkXRrvk4xozt7NjpQ7O8OV98hL3UaNsuwhr9h+Bj4WNtcEebxjWzzxIdHmyXsM1I9+HPkCEg6fAWttn6u2DyTYUp0+H3iFUYhxVS7a8CgA5ZWoJuE5v3G8KqoOLvvzV5L8txrzNY64a4zQnSobV42FKx+NwRmChAmQz8HyLO0IHaS77SWdopg6M=
  app: km-tracker-api
  on:
    repo: timbo/km-tracker-api
