# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b25386525ac312a11bf25150789b4b6a80b6753fa128ec8c573beb4fcf807c36b7b8d4ed00f372496217e554f8172bb968725b32f6bcdebbc1dc6d5e8613c5dc

test:
  secret_key_base: 652705615e971af32f8ec76b2984b08eccf9c398e144649bf4f6181b9f39895cc278cc19f771d02eca9a033d57872f223d1e703eb75ea373fd7e73ad5aa69723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
